apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flowfi-dev
resources:
  - namespace.yaml
  - ../../base
images:
  - name: flowfi/api
    newName: registry.digitalocean.com/vigasin-flowfi/flowfi/api
    newTag: dev
  - name: flowfi/web
    newName: registry.digitalocean.com/vigasin-flowfi/flowfi/web
    newTag: dev
  - name: flowfi/worker
    newName: registry.digitalocean.com/vigasin-flowfi/flowfi/worker
    newTag: dev
  - name: flowfi/indexer
    newName: registry.digitalocean.com/vigasin-flowfi/flowfi/indexer
    newTag: dev
