apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flowfi-dev
resources:
  - namespace.yaml
  - ../../base
images:
  - name: registry.digitalocean.com/vigasin-flowfi/flowfi/api
    newName: registry.digitalocean.com/vigasin-flowfi/flowfi/api
    newTag: de414bab6538
  - name: registry.digitalocean.com/vigasin-flowfi/flowfi/web
    newName: registry.digitalocean.com/vigasin-flowfi/flowfi/web
    newTag: de414bab6538
  - name: registry.digitalocean.com/vigasin-flowfi/flowfi/worker
    newName: registry.digitalocean.com/vigasin-flowfi/flowfi/worker
    newTag: de414bab6538
  - name: registry.digitalocean.com/vigasin-flowfi/flowfi/indexer
    newName: registry.digitalocean.com/vigasin-flowfi/flowfi/indexer
    newTag: de414bab6538
